site_name: My Docs

copyright: 'Copyright &copy; 2018 tnantoka'

extra_css:
  - css/extra.css

theme:
  name: material
  palette:
    primary: white
  logo:
    icon: home
  language: ja

extra:
  social:
    - type: github
      link: https://github.com/tnantoka
    - type: twitter
      link: https://twitter.com/tnantoka
